-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 23:53:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema payrollsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payrollsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payrollsystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `payrollsystem` ;

-- -----------------------------------------------------
-- Table `payrollsystem`.`reference_book_of_payroll_and_deductions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`reference_book_of_payroll_and_deductions` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `percent` DOUBLE NULL DEFAULT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`organization_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`organization_structure` (
  `code_post` INT(11) NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(100) NOT NULL,
  `post` VARCHAR(100) NOT NULL,
  `salary` DOUBLE NOT NULL,
  PRIMARY KEY (`code_post`),
  UNIQUE INDEX `code_post_UNIQUE` (`code_post` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`personal_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`personal_account` (
  `personal_number` INT(11) NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `post_code` INT(11) NOT NULL,
  `rate` DOUBLE NOT NULL,
  `bank_account` VARCHAR(45) NOT NULL,
  `mob_phone` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`personal_number`),
  INDEX `post_code_idx` (`post_code` ASC) VISIBLE,
  CONSTRAINT `post_code`
    FOREIGN KEY (`post_code`)
    REFERENCES `payrollsystem`.`organization_structure` (`code_post`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`deducation_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`deducation_sheet` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `month` INT(11) NOT NULL,
  `year` INT(11) NOT NULL,
  `code_post` INT(11) NOT NULL,
  `personal_number` INT(11) NOT NULL,
  `code_deducation` INT(11) NOT NULL,
  `sum_deducation` DOUBLE NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `code_post_idx` (`code_post` ASC) VISIBLE,
  INDEX `code_deducation_idx` (`code_deducation` ASC) VISIBLE,
  INDEX `personal_number_ded_idx` (`personal_number` ASC) VISIBLE,
  CONSTRAINT `code_ded`
    FOREIGN KEY (`code_deducation`)
    REFERENCES `payrollsystem`.`reference_book_of_payroll_and_deductions` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `code_post_ded`
    FOREIGN KEY (`code_post`)
    REFERENCES `payrollsystem`.`personal_account` (`post_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personal_number_ded`
    FOREIGN KEY (`personal_number`)
    REFERENCES `payrollsystem`.`personal_account` (`personal_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`payroll_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`payroll_sheet` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `month` INT(11) NOT NULL,
  `year` INT(11) NOT NULL,
  `code_post` INT(11) NOT NULL,
  `personal_number` INT(11) NOT NULL,
  `code_charges` INT(11) NOT NULL,
  `sum_charges` DOUBLE NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `code_charge_idx` (`code_charges` ASC) VISIBLE,
  INDEX `personal_number_charg_idx` (`personal_number` ASC) VISIBLE,
  INDEX `code_post_charg_idx` (`code_post` ASC) VISIBLE,
  CONSTRAINT `code_charges`
    FOREIGN KEY (`code_charges`)
    REFERENCES `payrollsystem`.`reference_book_of_payroll_and_deductions` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `code_post_charg`
    FOREIGN KEY (`code_post`)
    REFERENCES `payrollsystem`.`personal_account` (`post_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personal_number_charg`
    FOREIGN KEY (`personal_number`)
    REFERENCES `payrollsystem`.`personal_account` (`personal_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`users` (
  `idusers` INT(11) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `access` INT(11) NOT NULL,
  PRIMARY KEY (`idusers`),
  CONSTRAINT `id`
    FOREIGN KEY (`idusers`)
    REFERENCES `payrollsystem`.`personal_account` (`personal_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `payrollsystem`.`working_days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payrollsystem`.`working_days` (
  `number` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_number` INT(11) NOT NULL,
  `month` INT(11) NOT NULL,
  `year` INT(11) NOT NULL,
  `wasWorkedDays` INT(11) NOT NULL,
  `workingDays` INT(11) NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `personal_number_idx` (`personal_number` ASC) VISIBLE,
  CONSTRAINT `personal_number`
    FOREIGN KEY (`personal_number`)
    REFERENCES `payrollsystem`.`personal_account` (`personal_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
